import type { Metadata } from "next";
import {Poppins} from "next/font/google"
import {Nunito} from "next/font/google"
import {Merriweather_Sans} from "next/font/google"
import "./globals.css";
import DarkProvider from "@/app/_components/DarkProvider";
import Navbar from "@/app/_components/Navbar";
import {ClerkProvider, SignedOut, SignedIn, UserButton, SignInButton} from "@clerk/nextjs"

export const metadata: Metadata = {
  title: "Youth Tour.",
  description: "Generated by biswajit",
};

const mainHeadingText = Poppins({
  subsets: ["latin"],
  weight: ["200", "300", "100", "400", "600", "500", "700"],
  display: "swap"
})

const subHeadingText = Nunito({
  subsets: ["latin"],
  display: "swap",
  weight: "variable"
})

const contentText = Merriweather_Sans({
  subsets: ["latin"],
  weight: ["400", "300", "700", "800"],
  display: "swap",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider>
        <html lang="en" suppressHydrationWarning={true}>
        <body
            className={`${mainHeadingText.className} ${subHeadingText.className} ${contentText.className} max-w-screen-2xl min-h-screen antialiased`}
        >
        <DarkProvider>
           <Navbar/>
            <main
                className="relative w-full  h-full  px-5 bg-primary-white dark:bg-primary-black text-black dark:text-primary-white">{children}</main>
        </DarkProvider>
        </body>
        </html>
      </ClerkProvider>
  );
}
